// this should really be a database and an interface on the settings panel
exports.list = [
                "gay",
                "weed",
                "anal",
                "anus",
                "arse",
                " ass ", // dont be that kid who starts their sentence with the word ass, i will find you.
                "ballsack",
                "balls",
                "bastard",
                "bitch",
                "biatch",
                "bloody",
                "blowjob",
                "blow job",
                "bollock",
                "bollok",
                "boner",
                "boob",
                "bugger",
                "buttplug",
                "clitoris",
                "cock",
                "coon",
                "crap",
                "cunt",
                "damn",
                "dick",
                "dildo",
                "dyke",
                "fag",
                "feck",
                "fellate",
                "fellatio",
                "felching",
                "fuck",
                "f u c k",
                "fudgepacker",
                "fudge packer",
                "flange",
                "Goddamn",
                "God damn",
                " hell ",
                "homo",
                "jerk",
                "jizz",
                "knobend",
                "knob end",
                "labia",
                "lmao", // okay?
                "lmfao", // okay?
                "muff",
                "nigger",
                "nigga",
                "penis",
                "piss",
                "poop", // okay?
                "prick",
                "pube ",
                "pussy",
                "queer",
                "scrotum",
                "sex",
                "shit",
                "s hit",
                "sh1t",
                "slut",
                "smegma",
                "spunk",
                "tit",
                "tosser",
                "turd ",
                "twat",
                "vagina",
                "wank",
                "whore",
                "wtf"
              ];
exports.bannedWords = { // these messages wont even send
                "follow": "Requesting followers is not allowed.", // so people dont ask you to follow them on twitter.
                "phone": "Sharing phone numbers is not allowed.", // this could end badly ya kno
                "email": "Sharing email addresses is not allowed.", // sharing emails is not allowed
                "http": "Sharing links is not allowed.", // sharing links could be porn, partial filtering would be better
                ".com": "Sharing links is not allowed."
};